name: DRAM Price Bot

on:
  schedule:
    # 한국 시간 기준 오후 1시, 4시, 8시 자동 실행
    - cron: '0 4,7,11 * * *'
  workflow_dispatch: # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 필수 라이브러리 설치
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

      - name: 파이썬 코드 실행
        run: python 바탕화면고정코드.py # 실제 업로드한 파일 이름과 일치하는지 꼭 확인하세요!

      - name: 결과 파일 확인 및 업로드
        uses: actions/upload-artifact@v4
        with:
          name: dram-price-result
          path: ./*.xlsx
          if-no-files-found: error
